addSbtPlugin("com.typesafe.sbt"   % "sbt-twirl"          % "1.3.15")
addSbtPlugin("io.get-coursier"    % "sbt-coursier"       % "1.0.0")
addSbtPlugin("com.scalapenos"     % "sbt-prompt"         % "1.0.2")
addSbtPlugin("com.github.gseitz"  % "sbt-release"        % "1.0.7")
addSbtPlugin("com.frugalmechanic" % "fm-sbt-s3-resolver" % "0.14.0")
